DROP DATABASE IF EXISTS burgers_db;
CREATE DATABASE burgers_db; 
USE burgers_db; 

CREATE TABLE IF NOT EXISTS burgers (
	
	id INT(10) NOT NULL AUTO_INCREMENT,
	burger_name VARCHAR (255) NULL,
	devoured BOOLEAN DEFAULT NULL,
	time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);